### ISSUE TITLE
Dev04-K12 learning module

### ISSUE THREAD

**Issue by Avman2119** [Kentico/training-kentico-k12#28]
I just went through the creation of the Landing pages as well as the advanced widgets and when I try to load the following view for the landing page... 

`@section Styles {
    @Html.Kentico().PageBuilderStyles()
}

<div class="section">
    <div class="container">
        <div class="kn-system-messages"></div>
        @Html.Kentico().EditableArea("top")
    </div>
</div>

@section Scripts {
    @Html.Kentico().PageBuilderScripts()
}`

I get the following error: 

The following sections have been defined but have not been rendered for the layout page "~/Views/Shared/_Layout.cshtml": "Styles".

**Comment by JanLenoch** [comment]
Hi @Avman2119 , thanks for letting us know!

The problem was that I forgot to add an explicit instruction to add the respective `@RenderSection("Styles", required: false)` directive to the end of the `<head />` tag in the `_Layout.cshtml` file.

I've added the instruction, it will appear in the course soon.

Thanks again for reporting it!
