### ISSUE TITLE
Pagebuilder

### ISSUE THREAD

**Issue by aiminfogit** [Kentico/training-kentico-k12#43]
At least enable page tab for 1 page
At least implement 1 editable text box, widget, form in page tab.

**Comment by JanLenoch** [comment]
Hi @aiminfogit , I'm not sure what exactly you meant because the course actually tells how to implement an editable text widget. The finalized code in the [builders](https://github.com/Kentico/training-kentico-k12/tree/builders) branch also shows the usage of the built-in form widget. Once you check out this branch and restore the database, you will be able to see the landing page where all of that is being demonstrated.
Or, perhaps you meant something different. If that's the case, could you explain your intentions a bit more? Thanks.

**Comment by JanLenoch** [comment]
No response whatsoever. Closing.
