### ISSUE TITLE
HTTP Error 401.3 - Unauthorized

### ISSUE THREAD

**Issue by ecnerwal1234** [Kentico/training-kentico-k12#44]
I get this error trying to load the admin for the training site.  The forward facing site loads fine.

HTTP Error 401.3 - Unauthorized
You do not have permission to view this directory or page because of the access control list (ACL) configuration or encryption settings for this resource on the Web server.

**Comment by JanLenoch** [comment]
Hello @ecnerwal1234 , thanks for pointing this out!

The 401.3 HTTP error might most probably be caused by the lack of permissions in the file system. You may want to make sure either the IUSR built-in account or the whole IIS_IUSRS built-in user group has read & execute access to the CMS folder in your solution.

You can read more about these system built-in accounts at https://docs.microsoft.com/en-us/iis/get-started/planning-for-security/understanding-built-in-user-and-group-accounts-in-iis

Please let me know if adding the missing file system permissions helped. If that's the case, I'll add an explicit note into our course so that no one hits the same obstacle again.

Thanks

**Comment by ecnerwal1234** [comment]
the anonymous user was blank and adding this fixed this issue
![user fix](https://user-images.githubusercontent.com/6483075/72006362-736a2d00-321d-11ea-8b22-51f428552466.PNG)
